stages:
  - deploy:test
  - test:fabric
  - test:connectivity
  - deploy:prod
image: python:3.6

before_script:
  - pip install pyats[full] genie cryptography==3.3.1 requests cmlutils Jinja2==2.11.2 ansible==2.9.17 paramiko
  - chmod 0770 iac-infra/ansible

config_test:
  stage: deploy:test
  except:
    - master
  script:
    - cd iac-infra/ansible && ansible-playbook -i inventory/test.yml -e @../../vlan-fabric.yml deploy-vlan-fabric.yml

test_vlan_fabric:
  stage: test:fabric
  needs:
    - config_test
  except:
    - master
  when: delayed
  start_in: 1 minute
  script:
    - pyats run job iac-infra/tests/test-vlan-fabric.py

test_connectivity:
  stage: test:connectivity
  needs:
    - test_vlan_fabric
  except:
    - master
  script:
    - pyats run job iac-infra/tests/test-connectivity.py

config_prod:
  stage: deploy:prod
  only:
    - master
  script:
    - cd iac-infra/ansible && ansible-playbook -i inventory/prod.yml -e @../../vlan-fabric.yml deploy-vlan-fabric.yml