---
all:
  hosts:
    rtr-edge:
      ansible_host: 10.10.20.170
  children:
    core:
      hosts:
        sw-core:
          ansible_host: 10.10.20.171
    distribution:
      hosts:
        sw-dist-01:
          ansible_host: 10.10.20.172
        sw-dist-02:
          ansible_host: 10.10.20.173
    access:
      host:
        sw-acc-01:
          ansible_host: 10.10.20.174
